THAI_INDICATORS = ['coconut milk', 'fish sauce', 'chili pepper', 'galangal', 'curry']
# all found pasta types on https://en.wikipedia.org/wiki/List_of_pasta
PASTA_TYPES = [
    'barbine',
    'bavette',
    'bigoli',
    'bucatini',
    'busiate',
    'capellini',
    'fedelini',
    'ferrazuoli',
    'fettuccine',
    'fileja',
    'linguine',
    'lagane',
    'lasagna',
    'lasagnette',
    'lasagnotte',
    'maccheroni alla molinara',
    'maccheroncini di campofilone',
    'mafalde',
    'matriciani',
    'pappardelle',
    'perciatelli',
    'pici',
    'pillus',
    'rustiche',
    'sagne \'ncannulate',
    'scialatelli',
    'scialatielli',
    'spaghetti',
    'spaghettini',
    'spaghettoni',
    'stringozzi',
    'su filindeu',
    'taglierini',
    'trenette',
    'tripoline',
    'vermicelli',
    'ziti',
    'anelli',
    'boccoli',
    'bowtie',
    'calamarata',
    'campanelle',
    'torchio',
    'cappelli da chef',
    'casrecce',
    'castellane',
    'cavatappi',
    'cavatelli',
    'chifferi',
    'cicioneddos',
    'conchiglie',
    'creste di galli',
    'fagioloni',
    'farfalle',
    'fazzoletti',
    'festoni',
    'fiorentine',
    'fiori',
    'fusilli',
    'fusilli bucati',
    'garganelli',
    'gemelli',
    'gnocchi',
    'gomiti',
    'kusksu',
    'lanterne',
    'lorighittas',
    'maccheroni',
    'maccheroncelli',
    'mafaldine',
    'maltagliati',
    'malloreddus',
    'mandala',
    'marille',
    'mezzani',
    'mezze maniche',
    'mezze penne',
    'mezzi bombardoni',
    'nuvole',
    'paccheri',
    'passatelli',
    'pasta al ceppo',
    'penne',
    'penne rice',
    'picchiarelli',
    'pipe rigate',
    'pizzoccheri',
    'quadrefiore',
    'radiatori',
    'riccioli',
    'ricciolini',
    'ricciutelle',
    'rigatoncini',
    'rigatoni',
    'rombi',
    'rotelle',
    'rotini',
    'sagnette',
    'sagnarelli',
    'sedani',
    'spirali',
    'spiralini',
    'strapponi',
    'strozzapreti',
    'testaroli',
    'tortiglioni',
    'treccioni',
    'trenne',
    'trofie',
    'tuffoli',
    'vesuvio',
    'cencioni',
    'corzetti',
    'fainelle',
    'foglie d\'ulivo',
    'orecchiette',
    'acini di pepe',
    'anelli',
    'conchigliette',
    'corallini',
    'ditali',
    'ditalini',
    'egg barley',
    'farfalline',
    'fideos',
    'filini',
    'fregula',
    'funghini',
    'gramigne',
    'grattini',
    'grattoni',
    'midolline',
    'occhi di pernice',
    'orzo',
    'pastina',
    'pasta',
    'piombi',
    'ptitim',
    'puntine',
    'quadrettini',
    'sorprese',
    'stelle',
    'stortini',
    'tripolini',
    'alphabet pasta',
    'agnolotti',
    'caccavelle',
    'cannelloni',
    'cappelletti',
    'caramelle',
    'casoncelli',
    'casunziei',
    'conchiglioni',
    'culurgiones',
    'fagottini',
    'lumache',
    'macaroni',
    'mezzelune',
    'occhi di lupo',
    'pansotti',
    'ravioli',
    'rotolo ripieno',
    'sacchettoni',
    'tortellini',
    'tortelloni',
    'tortelli del mugello',
    'tufoli',
    'stock'
]

def transform_to_thai(recipe_data):
    input_ingredients = list(map(lambda i: i['name'], recipe_data['ingredients']))
    is_pasta_rice_soup = False
    
    # add sauces - coconut milk / fish sauce if dish is rice, a pasta, or soup
    for ig in input_ingredients:
        if any(map(lambda pasta_type: pasta_type in ig, PASTA_TYPES)):
            is_pasta_rice_soup = True
            
    if 'soup' in input_ingredients or 'rice' in input_ingredients:
        is_pasta_rice_soup = True
    
            
    return is_pasta_rice_soup
    
if __name__ == '__main__':
    # run tests
    sample_recipe = {'ingredients': [
        {'name': 'whole wheat lasagna noodles', 'quantity': 12, 'measurement': None, 'descriptor': None, 'preparation': None},
        {'name': 'ground beef', 'quantity': 1, 'measurement': 'pound', 'descriptor': 'lean', 'preparation': None},
        {'name': 'garlic', 'quantity': 2, 'measurement': 'cloves', 'descriptor': None, 'preparation': 'chopped'},
        {'name': 'garlic powder', 'quantity': 0.5, 'measurement': 'teaspoon', 'descriptor': None, 'preparation': None},
        {'name': 'oregano', 'quantity': 1, 'measurement': 'teaspoon or to taste', 'descriptor': 'dried', 'preparation': None},
        {'name': 'salt and ground black pepper', 'quantity': None, 'measurement': 'to taste', 'descriptor': None, 'preparation': None},
        {'name': 'cottage cheese', 'quantity': 1, 'measurement': '(16 ounce) package', 'descriptor': None, 'preparation': None},
        {'name': 'eggs', 'quantity': 2, 'measurement': None, 'descriptor': None, 'preparation': None},
        {'name': 'Parmesan cheese', 'quantity': 0.5, 'measurement': 'cup', 'descriptor': None, 'preparation': 'shredded'},
        {'name': 'tomato-basil pasta sauce', 'quantity': 1.5, 'measurement': '(25 ounce) jars', 'descriptor': None, 'preparation': None},
        {'name': 'mozzarella cheese', 'quantity': 2, 'measurement': 'cups', 'descriptor': None, 'preparation': 'shredded'}]
    }
    
    print(transform_to_thai(sample_recipe))