THAI_INDICATORS = ['coconut milk', 'fish sauce', 'chili pepper', 'galangal', 'curry']
# all found pasta types on https://en.wikipedia.org/wiki/List_of_pasta
PASTA_TYPES = [
    'barbine',
    'bavette',
    'bigoli',
    'bucatini',
    'busiate',
    'capellini',
    'fedelini',
    'ferrazuoli',
    'fettuccine',
    'fileja',
    'linguine',
    'lagane',
    'lasagna',
    'lasagnette',
    'lasagnotte',
    'maccheroni alla molinara',
    'maccheroncini di campofilone',
    'mafalde',
    'matriciani',
    'pappardelle',
    'perciatelli',
    'pici',
    'pillus',
    'rustiche',
    'sagne \'ncannulate',
    'scialatelli',
    'scialatielli',
    'spaghetti',
    'spaghettini',
    'spaghettoni',
    'stringozzi',
    'su filindeu',
    'taglierini',
    'trenette',
    'tripoline',
    'vermicelli',
    'ziti',
    'anelli',
    'boccoli',
    'bowtie',
    'calamarata',
    'campanelle',
    'torchio',
    'cappelli da chef',
    'casrecce',
    'castellane',
    'cavatappi',
    'cavatelli',
    'chifferi',
    'cicioneddos',
    'conchiglie',
    'creste di galli',
    'fagioloni',
    'farfalle',
    'fazzoletti',
    'festoni',
    'fiorentine',
    'fiori',
    'fusilli',
    'fusilli bucati',
    'garganelli',
    'gemelli',
    'gnocchi',
    'gomiti',
    'kusksu',
    'lanterne',
    'lorighittas',
    'maccheroni',
    'maccheroncelli',
    'mafaldine',
    'maltagliati',
    'malloreddus',
    'mandala',
    'marille',
    'mezzani',
    'mezze maniche',
    'mezze penne',
    'mezzi bombardoni',
    'nuvole',
    'paccheri',
    'passatelli',
    'pasta al ceppo',
    'penne',
    'penne rice',
    'picchiarelli',
    'pipe rigate',
    'pizzoccheri',
    'quadrefiore',
    'radiatori',
    'riccioli',
    'ricciolini',
    'ricciutelle',
    'rigatoncini',
    'rigatoni',
    'rombi',
    'rotelle',
    'rotini',
    'sagnette',
    'sagnarelli',
    'sedani',
    'spirali',
    'spiralini',
    'strapponi',
    'strozzapreti',
    'testaroli',
    'tortiglioni',
    'treccioni',
    'trenne',
    'trofie',
    'tuffoli',
    'vesuvio',
    'cencioni',
    'corzetti',
    'fainelle',
    'foglie d\'ulivo',
    'orecchiette',
    'acini di pepe',
    'anelli',
    'conchigliette',
    'corallini',
    'ditali',
    'ditalini',
    'egg barley',
    'farfalline',
    'fideos',
    'filini',
    'fregula',
    'funghini',
    'gramigne',
    'grattini',
    'grattoni',
    'midolline',
    'occhi di pernice',
    'orzo',
    'pastina',
    'pasta',
    'piombi',
    'ptitim',
    'puntine',
    'quadrettini',
    'sorprese',
    'stelle',
    'stortini',
    'tripolini',
    'alphabet pasta',
    'agnolotti',
    'caccavelle',
    'cannelloni',
    'cappelletti',
    'caramelle',
    'casoncelli',
    'casunziei',
    'conchiglioni',
    'culurgiones',
    'fagottini',
    'lumache',
    'macaroni',
    'mezzelune',
    'occhi di lupo',
    'pansotti',
    'ravioli',
    'rotolo ripieno',
    'sacchettoni',
    'tortellini',
    'tortelloni',
    'tortelli del mugello',
    'tufoli',
    'stock'
]

def transform_to_thai(recipe_data):
    input_ingredients = list(map(lambda i: i['name'], recipe_data['ingredients']))
    is_pasta_rice_soup = False
            
    return is_pasta_rice_soup